#!/bin/bash
#PBS -N t2_15000ncmc_mup_unr
#PBS -q glean
#PBS -A mobley-bergazin
#PBS -l nodes=1:ppn=4:gpu
#PBS -l walltime=200:00:00
#PBS -M bergazin@uci.edu
. $HOME/anaconda3/etc/profile.d/conda.sh
conda activate
conda activate wat
conda list
cd ${PBS_O_WORKDIR}
echo “Job directory: ${PBS_O_WORKDIR}”
echo "Nodes chosen are:"
cat $PBS_NODEFILE
module load cuda/9.1.85
nvcc -V
python mup_yaml.py
conda deactivate wat
